version: '2'
services:
  quasar_mongodb_read_only:
    container_name: quasar_mongodb_read_only
    image: mongo:3.4
    command: mongod --smallfiles
    ports:
      - "27020:27017"

  quasar_mongodb_3_2:
    container_name: quasar_mongodb_3_2
    image: mongo:3.2.19
    command: ["mongod", "--smallfiles", "--storageEngine", "ephemeralForTest"]
    ports:
      - "27021:27017"

  quasar_mongodb_3_4:
    container_name: quasar_mongodb_3_4
    image: mongo:3.4.3
    command: ["mongod", "--smallfiles", "--storageEngine", "ephemeralForTest"]
    ports:
      - "27022:27017"

  quasar_mongodb_3_4_13:
    container_name: quasar_mongodb_3_4_13
    image: mongo:3.4.13
    command: ["mongod", "--smallfiles", "--storageEngine", "ephemeralForTest"]
    ports:
      - "27023:27017"

  quasar_mongodb_3_6:
    container_name: quasar_mongodb_3_6
    image: mongo:3.6.3
    command: ["mongod", "--smallfiles", "--storageEngine", "ephemeralForTest"]
    ports:
      - "27024:27017"

  quasar_metastore:
    container_name: quasar_metastore
    image: postgres:9.6.5
    privileged: true
    ports:
      - "5432:5432"

  quasar_marklogic_xml:
    container_name: quasar_marklogic_xml
    build:
      context: ./Dockerfiles/Marklogic
      dockerfile: MarkLogic-Dockerfile
    ports:
      - "8000-8002:8000-8002"
    mem_limit: 2048m

  quasar_marklogic_json:
    container_name: quasar_marklogic_json
    build:
      context: ./Dockerfiles/Marklogic
      dockerfile: MarkLogic-Dockerfile
    ports:
      - "9000-9002:8000-8002"
    mem_limit: 2048m

  quasar_couchbase:
    container_name: quasar_couchbase
    image: couchbase/server:enterprise-4.5.1
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    mem_limit: 2560m
